### ISSUE TITLE
The bundle could not be installed on symfony 6.

### ISSUE THREAD

**Issue by juanma1331** [redantnl/twig-components-bundle#6]
When trying to install the bundle i get this. Do ive to wait for you to upgrade the bundle? Is something i can fix?. Thanks
![1](https://user-images.githubusercontent.com/46537115/152136641-bda2e466-3f66-4014-8d85-8e6a7e099509.png)
s

**Comment by ricohumme** [comment]
Hi @juanma1331,

Could you fork the project and see if this will work on SF 6? If everything is working, you can create a PR if you want.
We are currently not on a project with SF 6 so we won't have anything to test this on right now.

**Comment by juanma1331** [comment]
Im pretty new to web development in general, could you tell me what do ive to do exactly?. First Ive to fork the project, then? Is the first time i forked a project :D

**Comment by ricohumme** [comment]
Take a look over here:
https://getcomposer.org/doc/05-repositories.md#using-private-repositories
at repositories url point the twig-components-bundle to your version of it.
Then you can require the package via composer with `redant/twig-components-bundle` and it should fetch it from your repo.
Ofcourse before doing that, you should've updated the composer.json on your fork to allow SF 6.

Does that help?

**Comment by juanma1331** [comment]
Yes really thanks. Ill try

**Comment by ricohumme** [comment]
Seems like my colleague has created a SF 6 branch which you can checkout using `composer require redant/twig-components-bundle dev-sf6` :)

**Comment by juanma1331** [comment]
`composer require redant/twig-components-bundle dev-sf6` Throws the same error for me :(

**Comment by juanma1331** [comment]
Tried with a fresh Symfony install but got the same error.

**Comment by ricohumme** [comment]
Just checked. It works doing the following:
`composer require redant/twig-components dev-sf6  redant/twig-components-bundle dev-sf6`

**Comment by juanma1331** [comment]
Ill try. Please could you tell me in what points differ this library with ux-twig-components?

**Comment by cinamo** [comment]
@juanma1331 I've just updated the main branch, so you can just install on SF6 now.

**Comment by cinamo** [comment]
The difference with ux-twig-components ... well, they have an approach where you define the component mostly in PHP code, this library uses Twig for that.

**Comment by juanma1331** [comment]
Prefer not to have to declare a php class for every component. Thanks both for your time. Ill try again.
